### ISSUE TITLE
incorrect path depth

### ISSUE THREAD

**Issue by crobinson42** [AlbertoFdzM/express-list-endpoints#10]
The correct path is not being parsed on multi-level `baseRoute`, ie:

```
const express = require('express')
const router = express.Router()

router.route('/my/path').get(()=>{ /* someMethod() */ })

app.use("/api/multi/level", router)
```

will output:

```
[ { path: '/api/my/path',
    methods: [ 'GET' ] } ]
```

the output path ^^^^ is incorrect - and the endpoint `/api/multi/level/my/path` DOES exist when starting up the server and hitting it in the browser.

**Comment by AlbertoFdzM** [comment]
Right! I didn't cover that use case.

Will work on it.
