### ISSUE TITLE
Not generating full path of endpoints

### ISSUE THREAD

**Issue by cfranc0** [AlbertoFdzM/express-list-endpoints#51]
My app contains a lot different endpoints and many are spread within different files.
For this reason, the path on the endpoint is not complete, but the section I'm implementing in that file.

I'm not great at explaining, so here's some examples:
I created an entry point with
`app.use(['/auth'], require('./auth/index.js'));`
and in that file I have both 
`router.post('/', async (req, res) => {...})` and `router.use('/verify', require('./verifyEmail'));` (which will contain some other endpoints)
meaning that endpoints do not have the complete url they are associated to because the previous bits are defined in the "father" file.

At this point, this is what the script generates:
![image](https://user-images.githubusercontent.com/20073894/65357021-245ca580-dbf6-11e9-9a67-06211169b323.png)
Note all the methods for the '/' path, those are, in reality, spread across different routes and represent only the final step.

As I said, my explanation could be much better. If you need any further info, don't hesitate to reach out!

**Comment by tgerk** [comment]
My little research on this problem found that the `regexpExpressRegexp` may be root of the issue.  it does not match my API router's root path, created like this:
```
app.use(/^\/v(1(?:\.\d+)?)/i, router);
```

The result starts `[ { path: '/login', methods: [ 'GET', 'POST' ] }, ...` instead of like `[ { path: '/v:0/login', methods: [ 'GET', 'POST' ] }, ...`

```
    "express": "^4.17.1",
    "express-list-endpoints": "^4.0.1",
```

**Comment by emirhg** [comment]
Maybe this pull request fixes it: https://github.com/AlbertoFdzM/express-list-endpoints/pull/52

I had a similar problem and fixed the regex, but it was 2 months ago and i forget exactly how to make it crash.
