### ISSUE TITLE
require statement not part of an import statement

### ISSUE THREAD

**Issue by greenpau** [AlbertoFdzM/express-list-endpoints#56]
In the `README.md`, there is the following definition.

```
const listEndpoints = require('express-list-endpoints')
```

It causes linter to fails:

```
src/app/server.ts
[Error 10,23]: require statement not part of an import statement (no-var-requires)
[Error 10,31]: ' should be " (quotemark)
```

Opening the issue in case someone else runs into this same issue. Here is how I rewrote the statement.

```js
//const listEndpoints = require('express-list-endpoints')
import * as ListExpressEndpoints from "express-list-endpoints";

// Display endpoints
log(ListExpressEndpoints(express));
```

**Comment by AlbertoFdzM** [comment]
Seems that you're using some TypeScript REPL to be used with this package (like ts-node).

The documentation of this package is intended to be used with NodeJS using javascript. Since the package docs do not have yet a section of how to be used with typescript I'm closing this issue.
