### ISSUE TITLE
Parse route parameters including a trailing regexp

### ISSUE THREAD

**Issue by AlbertoFdzM** [AlbertoFdzM/express-list-endpoints#72]
As a user
I want the tool to be able to parse routes like `/users/:userId(\d+)`
So that I can list this endpoints too

### Additional Context

Express Documentation for Route Parameters: https://expressjs.com/en/guide/routing.html#route-parameters

PR: https://github.com/AlbertoFdzM/express-list-endpoints/pull/52

CC: @emirhg

**Comment by nwalters512** [comment]
@AlbertoFdzM I saw this issue after I opened #91, I think that PR will resolve this! Would you be able to take a look at that PR soon?
