### ISSUE TITLE
Great util! Thx

### ISSUE THREAD

**Issue by crobinson42** [AlbertoFdzM/express-list-endpoints#9]
Let me know if you need any help maintaining this. I was just about to build this module myself after getting frustrated at the other `express-list-routes` module being poorly written, when I found this!

**Comment by crobinson42** [comment]
I've got a couple ideas for features I could quickly implement like a cli-table formatter making the output a lot more pretty in the terminal.

**Comment by AlbertoFdzM** [comment]
Hey, thank for your comment! Don't doubt in hit me with as much Pull Request as you like.

You can start creating issues about the ideas you've got for this packages, by that way we can comment them and work together on these features.
